accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("profile/", views.update_profile, name='profile'),
    path("u/<str:username>/", views.public_profile, name='public-profile')
]

posts/urls.py
from django.urls import path, include
from .views import (
            Index,
            PostDelete,
            create_post,
            PostDetail,
            delete_comment,
            update_post,
            PostDelete,
            delete_post_htmx,
            create_post_form,
            update_post_form,
            search,
            create_comment_form,
            delete_comment,
            htmx_post_list,
            ajax_post_list
            )

app_name = 'posts'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('<slug:slug>/detail/', PostDetail.as_view(), name='detail'),
    path('<slug:slug>/update/', update_post, name='update'),
    path('<slug:slug>/comment/',create_comment_form, name='comment'),
    path('<slug:slug>/htmx_update/', update_post_form, name='htmx-update'),
    path('<slug:slug>/delete/', PostDelete.as_view(), name="delete"),
    path('create/', create_post, name="create"),
    path('delete_comment/<int:pk>/', delete_comment, name='delete-comment'),
    path('search/', search, name="search"),
    path('htmx_delete/<slug:slug>/', delete_post_htmx, name='htmx-delete'),
    path('htmx_create/', create_post_form, name='htmx-create'),
    path('htmx_post_list/', htmx_post_list, name='htmx-post-list'),
    path('ajax_post_list/', ajax_post_list, name='ajax-post-list')
    ]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts import urls

urlpatterns = [
    path('', include("posts.urls", namespace="posts")),
    # admin
    path('admin/', admin.site.urls),
    # allauth & accounts
    path('accounts/', include('allauth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from autoslug import AutoSlugField
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.db import models


from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation



class CustomPostManger(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('-added')


class CustomCommentManger(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('-added')


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="title")
    body = models.TextField()
    image = models.ImageField(upload_to='images/', default='images/blank.png')
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(150, 150)],
                                      format='JPEG',
                                      options={'quality': 60})
    creator = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    added = models.DateTimeField(auto_now_add=True)
    hit_count_generic = GenericRelation(
                HitCount,
                object_id_field='object_pk',
                related_query_name='hit_count_generic_relation'
                )

    objects = CustomPostManger()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs = {'slug': self.slug})
    
    def get_update_url(self):
        return reverse('posts:update', kwargs = {'slug': self.slug})
    
    def get_add_comment_url(self):
        return reverse('posts:comment', kwargs = {'slug': self.slug})

    @property
    def comments(self):
        return Comment.objects.filter(post=self)
    
    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count() 

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    comment = models.TextField()
    added = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=True)

    objects = CustomCommentManger()

    def __str__(self):
        return f"{self.user} on {self.post}"
    
    def get_delete_url(self):
        return reverse('posts:delete-comment', kwargs = {'pk': self.pk})

posts/forms.py
from xml.dom import ValidationErr
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'image']
        widgets = {
            'body': forms.Textarea(attrs={
                'rows': 10,
                'cols': 40,
                'class': 'materialize-textarea'
                }),
        }
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment',]
        widgets = {
            'comment': forms.Textarea(attrs={
                'rows': 10,
                'cols': 20,
                'class': 'materialize-textarea',
                'data-length': '500'
                }),
        }

    def clean_comment(self):
        data = self.cleaned_data['comment']
        if len(data) > 500:
            msg = 'Comment is too long. Please keep your comment under 500 characters.'
            self.add_error('comment', msg)
        if len(data) < 5:
            msg = 'Comment is too short.'
            self.add_error('comment', msg)
        return data

posts/views.py
import time

from django.http import HttpResponseNotAllowed, HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView, DeleteView
from hitcount.views import HitCountDetailView

from .mixins import UserIsOwnerMixin
from .models import Post, Comment
from .forms import PostForm, CommentForm

class Index(ListView):
    paginate_by = 8
    model = Post
    template_name = 'posts/index.html'
    
    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context.update({
        'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:5],
        'recent_posts': Post.objects.order_by('-added')[:5]
        })
        return context  

class PostDetail(HitCountDetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context.update({
        'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:5],
        'recent_posts': Post.objects.order_by('-added')[:5],
        'form': CommentForm()
        })
        return context    
 
class PostDelete(UserIsOwnerMixin, LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'
    success_url = reverse_lazy('posts:index')

@login_required
def create_post(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.creator = request.user
            new_post.save()
            messages.success(request, 'New post created successfully')
            return redirect(new_post.get_absolute_url())
        else:
            messages.success(request, 'Please correct errors in form an try agin')
            form = PostForm(request.POST, request.FILES or None)
    
    form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def update_post(request, slug):
    p = Post.objects.get(slug=slug)
    
    if p.creator != request.user:
        messages.error(request, 'Ownership error! You are not allowed to edit this post.')
        return redirect(p.get_absolute_url())
    
    form = PostForm(instance=p)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None, instance=p)
        if form.is_valid():
            p.title = form.cleaned_data['title']
            p.body = form.cleaned_data['body']
            p.image = form.cleaned_data['image']
            p.save()
            messages.success(request, 'Post updated successfully')
            context = {
                'post': p,
                'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:5],
                'recent_posts': Post.objects.order_by('-added')[:5]
            }
            return redirect(p.get_absolute_url())
        else:
            messages.error(request, 'Please correct errors in form an try agin')
            form = PostForm(request.POST, request.FILES or None)
    
    context = {
        'post': p,
        'form': form
    }
    return render(request, 'posts/update_post.html', context)


@login_required
@require_http_methods(['DELETE'])
def delete_post_htmx(request, slug):
    post = Post.objects.get(slug=slug)
    post.delete()
    posts = Post.objects.all()
    context = {
        'post_list': posts
    }
    return render(request, 'posts/_post_list.html', context)


# HTMX form to return in partial template
@login_required
def create_post_form(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            form.save()
            posts = Post.objects.all()
            context = {
                'post_list': posts
            }
            return render(request, 'posts/_post_list.html', context)
        else:
            form = PostForm(request.POST, request.FILES or None)
            context = {
                'form': form
            }
            return render(request, 'posts/create_post.html', context)
    
    form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'posts/_post_form.html', context)


@login_required
def update_post_form(request, slug):
    p = Post.objects.get(slug=slug)
    form = PostForm(instance=p)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            p.title = form.cleaned_data['title']
            p.body = form.cleaned_data['body']
            p.image = form.cleaned_data['image']
            p.save()

            context = {
                'post': p
            }

            return redirect(p.get_absolute_url())
        else:
            form = PostForm(request.POST, request.FILES or None)
    
    context = {
        'post': p,
        'form': form
    }
    return render(request, 'posts/_post_update_form_htmx.html', context)


@login_required
def create_comment_form(request, slug):
    p = Post.objects.get(slug=slug)
    
    if request.method == 'POST':
        form = CommentForm(request.POST or None)
        if form.is_valid():
            c = form.save(commit=False)
            c.post = p
            c.user = request.user
            c.save()
            new_comment = Comment.objects.get(pk=c.pk)
            form = CommentForm()
            context = {
                'comment': new_comment,
            }
            time.sleep(0.3)
            return render(request, 'posts/_comment.html', context)
        else:
            form = CommentForm(request.POST or None)
            context = {
                'post': p,
                'form': form,
            }
            return render(request, 'posts/_comment_form.html', context)
    context = {
        'post': p,
        'form': CommentForm()
    }
    return render(request, 'posts/_comment_form.html', context)


@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    context = {
        'pk': comment.pk
    }
    if request.method == 'POST':
        if request.user == comment.user:
            time.sleep(0.3)
            comment.delete()
            return render(request, 'posts/htmx/_htmx_comment_deleted.html', context)
        return HttpResponseForbidden('Not Allowed')

    return HttpResponseNotAllowed( ['POST'], 'Not Allowed')


def htmx_post_list(request):
    context = {
        'post_list': Post.objects.all()
    }
    return render(request, 'posts/_post_list.html', context)


def ajax_post_list(request):
    post_list = list(Post.objects.values())
    return JsonResponse(post_list, safe=False)


def search(request):
    qs = Post.objects.all()
    q = request.GET.get('q')
    if q and q != '':
        qs = qs.filter(
                Q(title__icontains=q) |
                Q(body__icontains=q)
                ).distinct()
        context = {
            'post_list': qs,
            'keyword': q
        }
        return render(request, 'posts/search_results.html', context)
        
    context = {
        'post_list': ''
    }
    return render(request, 'posts/search_results.html', context)

posts/templates/base.html
{% load static %}
{% load materializecss %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">  
  
    <!--Import materialize.css-->
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!-- Font Awesome-->
    <script src="https://kit.fontawesome.com/c2dba015b9.js" crossorigin="anonymous"></script>

  <!-- htmx CDN -->
  <script src="https://unpkg.com/htmx.org@1.8.0"
          integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc"
          crossorigin="anonymous"></script>

    <!--mobile optimiztion -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Django Starter | {% block title %}{% endblock title %}</title>
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

<div class="navbar-fixed">
    <nav class="purple darken-3">
        <div class="container">
            <!-- Nav Dropdown -->
            <ul id="dropdown1" class="dropdown-content">
                <li>
                    <a href="{% url 'accounts:profile' %}">Profile</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="{% url 'account_logout' %}">Logout</a>
                </li>
            </ul>
            <!-- end nav dropdown -->
            <div class="nav-wrapper">
                <a href="/" class="brand-logo flow-text hide-on-small-only">Django Starter</a>
                <a href="/" class="brand-logo hide-on-med-and-up"><i class="material-icons">home</i></a>
                <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>

                
                <ul class="right hide-on-med-and-down">
                    <li>
                        <a href="/">Posts</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'posts:create' %}">Add+</a>
                    </li>

                    <!-- Dropdown Trigger -->
                    <li><a class="dropdown-trigger btn-floating" href="#!" data-target="dropdown1">
                        <img src="{{ user.userprofile.avatar_thumbnail.url }}" class="avatar responsive-img">
                        </a>
                                               
                    </li>

                    {% else %}
                    <li>
                        <a href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'account_signup' %}">Signup</a>
                    </li>
                    {% endif %}
                   
                </ul>
            </div>

            
        </div>
    </nav>
    
</div>
<!-- Nav search bar -->
<nav class="deep-purple lighten-4">
    <div class="nav-wrapper">
      <form action="/search">
        <div class="input-field">
          <input id="search" type="search" name="q" required">
          <label class="label-icon" for="search"><i class="material-icons deep-purple-text">search</i></label>
          <i class="material-icons">close</i>
        </div>
      </form>
    </div>
</nav>
<!-- sidenav slideout -->
<ul id="slide-out" class="sidenav">
    {% if user.is_authenticated %}
    <li>
        <div class="user-view">
            <div class="background">
                <img src="{% static 'images/office.jpg' %}">
            </div>
            <a href="#user"><img class="circle" src="{{ user.userprofile.avatar_thumbnail.url }}"></a>
            <a href="#name"><span class="white-text name">{{ user.username }}</span></a>
            <a href="#email"><span class="white-text email">{{ user.email }}</span></a>
        </div>
    </li>
    {% else %}
    <li>
        <div class="user-view">
            <div class="background">
                <img src="{% static 'images/office.jpg' %}">
            </div>
            <a href="#user"><img class="circle" src="/media/avatars/user_avatar.png"></a>
            <a href="#name"><span class="white-text name">guest</span></a>
            <a href="#email"><span class="white-text email"></span></a>
        </div>
    </li>
    {% endif %}

    <li><a class="waves-effect" href="/"><i class="material-icons">home</i>Home</a></li>
    <li><a class="waves-effect" href="/"><i class="material-icons">list</i>Posts</a></li>
    <li><a class="waves-effect" href="{% url 'posts:create' %}"><i class="material-icons">add</i>New Post</a></li>
    <li>
        <div class="divider"></div>
    </li>
    <li><a class="subheader">Account</a></li>
    {% if user.is_authenticated %}
    <li><a class="waves-effect" href="{% url 'accounts:profile' %}"><i class="material-icons">account_circle</i>Profile</a>
    </li>
    <li><a class="waves-effect" href="{% url 'account_logout' %}"><i class="material-icons">highlight_off</i>Logout</a>
    </li>
    {% else %}
    <li><a class="waves-effect" href="{% url 'account_login' %}"><i class="material-icons">exit_to_app</i>Login</a></li>
    <li><a class="waves-effect" href="{% url 'account_signup' %}"><i class="material-icons">launch</i>Signup</a></li>
    {% endif %}
</ul>

<div class="container">
    <!-- Messages list -->
    {% if messages %}
    <ul id="messages-queue" class="collection purple-text text-darken-4" style="display: none;">
        {% for message in messages %}
        <li id="dj-msg" {% if message.tags %} class="{{ message.tags }} collection-item indigo lighten-5" {% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block content %}

    {% endblock content %}
</div>
<div class="section"></div>

{% block script %}

{% endblock script %}
  
    <script src="{% static 'js/materialize.min.js' %}"></script>

<script>
        
        // floatin action buttons init
        document.addEventListener('DOMContentLoaded', function() {
        var fab = document.querySelectorAll('.fixed-action-btn');
        var instances = M.FloatingActionButton.init(fab, {});
        });
        // end floating action buttons

        // dropdown
        document.addEventListener('DOMContentLoaded', function() {
        var drop = document.querySelectorAll('.dropdown-trigger');
        var instances = M.Dropdown.init(drop, {});
        });

        // Create Post Modal
        document.addEventListener('DOMContentLoaded', function() {
        var pmodal = document.querySelectorAll('.modal');
        var instances = M.Modal.init(pmodal, {});
        });

        // Materialize side nav init
        document.addEventListener('DOMContentLoaded', function() {
        var snav = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(snav, {});
        });

        /* date picker materialized css */
        document.addEventListener('DOMContentLoaded', function() {
        var dp = document.querySelectorAll('.datepicker');
        var instances = M.Datepicker.init(dp, {
          'isRTL': false
        });
        });

        // Materialized CSS Collapsible init
        document.addEventListener('DOMContentLoaded', function() {
        var collaps = document.querySelectorAll('.collapsible');
        var instances = M.Collapsible.init(collaps, {});
        });

        // show messages as materialize toast
        document.addEventListener('DOMContentLoaded', function msgToast() {
              const msgEl = document.getElementById('dj-msg')
              if (msgEl != null) {
                let msg = msgEl.textContent
                M.toast({html: msg }) 
            }
          })
    

</script>
</body>
</html>