posts/urls.py
from django.urls import path, include
from .views import (
            Index,
            PostDelete,
            create_post,
            PostDetail,
            delete_comment,
            update_post,
            PostDelete,
            delete_post_htmx,
            create_post_form,
            update_post_form,
            search,
            create_comment_form,
            delete_comment,
            htmx_post_list,
            ajax_post_list
            )

app_name = 'posts'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('<slug:slug>/detail/', PostDetail.as_view(), name='detail'),
    path('<slug:slug>/update/', update_post, name='update'),
    path('<slug:slug>/comment/',create_comment_form, name='comment'),
    path('<slug:slug>/htmx_update/', update_post_form, name='htmx-update'),
    path('<slug:slug>/delete/', PostDelete.as_view(), name="delete"),
    path('create/', create_post, name="create"),
    path('delete_comment/<int:pk>/', delete_comment, name='delete-comment'),
    path('search/', search, name="search"),
    path('htmx_delete/<slug:slug>/', delete_post_htmx, name='htmx-delete'),
    path('htmx_create/', create_post_form, name='htmx-create'),
    path('htmx_post_list/', htmx_post_list, name='htmx-post-list'),
    path('ajax_post_list/', ajax_post_list, name='ajax-post-list')
    ]

src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from posts import urls

urlpatterns = [
    path('', include("posts.urls", namespace="posts")),
    # admin
    path('admin/', admin.site.urls),
    # allauth & accounts
    path('accounts/', include('allauth.urls')),
    path('accounts/', include("accounts.urls", namespace="accounts"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from autoslug import AutoSlugField
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.db import models


from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation



class CustomPostManger(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('-added')


class CustomCommentManger(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('-added')


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(unique=True, always_update=False, populate_from="title")
    body = models.TextField()
    image = models.ImageField(upload_to='images/', default='images/blank.png')
    image_thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(150, 150)],
                                      format='JPEG',
                                      options={'quality': 60})
    creator = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    added = models.DateTimeField(auto_now_add=True)
    hit_count_generic = GenericRelation(
                HitCount,
                object_id_field='object_pk',
                related_query_name='hit_count_generic_relation'
                )

    objects = CustomPostManger()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs = {'slug': self.slug})
    
    def get_update_url(self):
        return reverse('posts:update', kwargs = {'slug': self.slug})
    
    def get_add_comment_url(self):
        return reverse('posts:comment', kwargs = {'slug': self.slug})

    @property
    def comments(self):
        return Comment.objects.filter(post=self)
    
    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count() 

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comments')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    comment = models.TextField()
    added = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=True)

    objects = CustomCommentManger()

    def __str__(self):
        return f"{self.user} on {self.post}"
    
    def get_delete_url(self):
        return reverse('posts:delete-comment', kwargs = {'pk': self.pk})

posts/forms.py
from xml.dom import ValidationErr
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'image']
        widgets = {
            'body': forms.Textarea(attrs={
                'rows': 10,
                'cols': 40,
                'class': 'materialize-textarea'
                }),
        }
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment',]
        widgets = {
            'comment': forms.Textarea(attrs={
                'rows': 10,
                'cols': 20,
                'class': 'materialize-textarea',
                'data-length': '500'
                }),
        }

    def clean_comment(self):
        data = self.cleaned_data['comment']
        if len(data) > 500:
            msg = 'Comment is too long. Please keep your comment under 500 characters.'
            self.add_error('comment', msg)
        if len(data) < 5:
            msg = 'Comment is too short.'
            self.add_error('comment', msg)
        return data

posts/views.py
import time

from django.http import HttpResponseNotAllowed, HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView, DeleteView
from hitcount.views import HitCountDetailView

from .mixins import UserIsOwnerMixin
from .models import Post, Comment
from .forms import PostForm, CommentForm

class Index(ListView):
    paginate_by = 8
    model = Post
    template_name = 'posts/index.html'
    
    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context.update({
        'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:5],
        'recent_posts': Post.objects.order_by('-added')[:5]
        })
        return context  

class PostDetail(HitCountDetailView):
    model = Post
    template_name = 'posts/post_detail.html'
    count_hit = True

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context.update({
        'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:5],
        'recent_posts': Post.objects.order_by('-added')[:5],
        'form': CommentForm()
        })
        return context    
 
class PostDelete(UserIsOwnerMixin, LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'
    success_url = reverse_lazy('posts:index')

@login_required
def create_post(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.creator = request.user
            new_post.save()
            messages.success(request, 'New post created successfully')
            return redirect(new_post.get_absolute_url())
        else:
            messages.success(request, 'Please correct errors in form an try agin')
            form = PostForm(request.POST, request.FILES or None)
    
    form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def update_post(request, slug):
    p = Post.objects.get(slug=slug)
    
    if p.creator != request.user:
        messages.error(request, 'Ownership error! You are not allowed to edit this post.')
        return redirect(p.get_absolute_url())
    
    form = PostForm(instance=p)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None, instance=p)
        if form.is_valid():
            p.title = form.cleaned_data['title']
            p.body = form.cleaned_data['body']
            p.image = form.cleaned_data['image']
            p.save()
            messages.success(request, 'Post updated successfully')
            context = {
                'post': p,
                'popular_posts': Post.objects.order_by('-hit_count_generic__hits')[:5],
                'recent_posts': Post.objects.order_by('-added')[:5]
            }
            return redirect(p.get_absolute_url())
        else:
            messages.error(request, 'Please correct errors in form an try agin')
            form = PostForm(request.POST, request.FILES or None)
    
    context = {
        'post': p,
        'form': form
    }
    return render(request, 'posts/update_post.html', context)


@login_required
@require_http_methods(['DELETE'])
def delete_post_htmx(request, slug):
    post = Post.objects.get(slug=slug)
    post.delete()
    posts = Post.objects.all()
    context = {
        'post_list': posts
    }
    return render(request, 'posts/_post_list.html', context)


# HTMX form to return in partial template
@login_required
def create_post_form(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            form.save()
            posts = Post.objects.all()
            context = {
                'post_list': posts
            }
            return render(request, 'posts/_post_list.html', context)
        else:
            form = PostForm(request.POST, request.FILES or None)
            context = {
                'form': form
            }
            return render(request, 'posts/create_post.html', context)
    
    form = PostForm()
    context = {
        'form': form
    }
    return render(request, 'posts/_post_form.html', context)


@login_required
def update_post_form(request, slug):
    p = Post.objects.get(slug=slug)
    form = PostForm(instance=p)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES or None)
        if form.is_valid():
            p.title = form.cleaned_data['title']
            p.body = form.cleaned_data['body']
            p.image = form.cleaned_data['image']
            p.save()

            context = {
                'post': p
            }

            return redirect(p.get_absolute_url())
        else:
            form = PostForm(request.POST, request.FILES or None)
    
    context = {
        'post': p,
        'form': form
    }
    return render(request, 'posts/_post_update_form_htmx.html', context)


@login_required
def create_comment_form(request, slug):
    p = Post.objects.get(slug=slug)
    
    if request.method == 'POST':
        form = CommentForm(request.POST or None)
        if form.is_valid():
            c = form.save(commit=False)
            c.post = p
            c.user = request.user
            c.save()
            new_comment = Comment.objects.get(pk=c.pk)
            form = CommentForm()
            context = {
                'comment': new_comment,
            }
            time.sleep(0.3)
            return render(request, 'posts/_comment.html', context)
        else:
            form = CommentForm(request.POST or None)
            context = {
                'post': p,
                'form': form,
            }
            return render(request, 'posts/_comment_form.html', context)
    context = {
        'post': p,
        'form': CommentForm()
    }
    return render(request, 'posts/_comment_form.html', context)


@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    context = {
        'pk': comment.pk
    }
    if request.method == 'POST':
        if request.user == comment.user:
            time.sleep(0.3)
            comment.delete()
            return render(request, 'posts/htmx/_htmx_comment_deleted.html', context)
        return HttpResponseForbidden('Not Allowed')

    return HttpResponseNotAllowed( ['POST'], 'Not Allowed')


def htmx_post_list(request):
    context = {
        'post_list': Post.objects.all()
    }
    return render(request, 'posts/_post_list.html', context)


def ajax_post_list(request):
    post_list = list(Post.objects.values())
    return JsonResponse(post_list, safe=False)


def search(request):
    qs = Post.objects.all()
    q = request.GET.get('q')
    if q and q != '':
        qs = qs.filter(
                Q(title__icontains=q) |
                Q(body__icontains=q)
                ).distinct()
        context = {
            'post_list': qs,
            'keyword': q
        }
        return render(request, 'posts/search_results.html', context)
        
    context = {
        'post_list': ''
    }
    return render(request, 'posts/search_results.html', context)

posts/templates/posts/_comment.html
<li id="comment-{{comment.pk}}" class="collection-item avatar grey lighten-4"
            hx-target="this"
            hx-swap="outerHTML">
    <img src="{{ comment.user.userprofile.avatar_thumbnail.url }}" alt="" class="circle">
    <span class="green-text text-darken-5"><b>Your comment was posted</b></span><br>
    <span class="title"><b>{{comment.user.userprofile.name}}</b></span>
    <p><span class="grey-text">{{comment.added|timesince}} ago</span>
      <br>
       {{comment.comment|linebreaks}}
    </p>
    
    {% if user.is_authenticated and user == comment.user %}
    <form hx-post="{{ comment.get_delete_url }}" method="post" class="secondary-content">
        {% csrf_token %}
        <div id="indicator" class="htmx-indicator preloader-wrapper small active">
            <div class="spinner-layer spinner-green-only">
                <div class="circle-clipper left">
                <div class="circle"></div>
                </div><div class="gap-patch">
                <div class="circle"></div>
                </div><div class="circle-clipper right">
                <div class="circle"></div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-flat waves-effect waves-red transparent grey-text">
            <i class="material-icons tiny grey-text">delete</i>
        </button>
    </form>
  {% endif %}

    
  </li>

posts/templates/posts/_comment_form.html
{% load materializecss %}
<li hx-target="this" class="collection-item avatar">
  <img src="{{ user.userprofile.avatar_thumbnail.url }}" alt="" class="circle">
      <div  hx-swap="outerHTML">
        <form hx-post="{{ post.get_add_comment_url }}" method='POST'>
          {% csrf_token %}
          {{ form|materializecss }}
            <button
            class="btn waves-effect waves-light blue right" type="submit" name="action">Post
                <i class="material-icons right">send</i>
        </button>
       
        <div id="indicator" class="htmx-indicator preloader-wrapper small active">
          <div class="spinner-layer spinner-green-only">
              <div class="circle-clipper left">
              <div class="circle"></div>
              </div><div class="gap-patch">
              <div class="circle"></div>
              </div><div class="circle-clipper right">
              <div class="circle"></div>
              </div>
          </div>
        </div>
        </form>
      </div>
</li>
<!-- end comment form -->

posts/templates/posts/_comment_list.html
        <ul id="comments-ul" class="collection">

          <li id="comment-form-li" class="collection-item">
            {% if user.is_authenticated %}
            <span>
                <button class="btn blue wave-effects" hx-get="{% url 'posts:comment' post.slug %}"
                hx-target="#comment-form-li"        
                hx-swap="outerHTML">Leave a comment</button>
            </span>
            {% else %}
            <p class="">Please <a href="{% url 'account_login' %}?next={{ post.get_absolute_url }}">login</a> to leave a comment.</p>
            {% endif %}
          </li>
          {% for comment in post.comments %}
            <li id="comment-{{comment.pk}}" class="collection-item avatar">
              <a href="{{ comment.user.userprofile.get_public_profile_url }}">
              <img src="{{ comment.user.userprofile.avatar_thumbnail.url }}" alt="" class="circle" />
            </a>
              <span class="title"><a href="{{ comment.user.userprofile.get_public_profile_url }}">
                {{comment.user.userprofile.name}}</a></span>
              <p style="margin-top: 2px;"><span class="grey-text">{{comment.added}}</span>
                <br>
                 {{comment.comment|linebreaks}}
              </p>
              
              {% if user.is_authenticated and user == comment.user %}
              <form hx-post="{{ comment.get_delete_url }}" method="post"
                class="secondary-content"
                hx-target="#comment-{{comment.pk}}"
                hx-swap="outerHTML"> 
                {% csrf_token %}
                <div id="indicator" class="htmx-indicator preloader-wrapper small active">
                  <div class="spinner-layer spinner-green-only">
                      <div class="circle-clipper left">
                      <div class="circle"></div>
                      </div><div class="gap-patch">
                      <div class="circle"></div>
                      </div><div class="circle-clipper right">
                      <div class="circle"></div>
                      </div>
                  </div>
                </div>
                <button type="submit" class="btn btn-flat waves-effect waves-red transparent grey-text">
                  <i class="material-icons tiny grey-text">delete</i>
                </button>
                
              </form>
            {% endif %}

              <!-- <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a> -->
            </li>
          {% endfor %}
          </ul>

posts/templates/posts/_post_form.html
{% load materializecss %}
<!--  post form for Modal partial template -->
<div>
    <h5 class="grey-text">Add a new post</h5>
    <form action="{% url 'posts:create' %}" method='POST' enctype="multipart/form-data" class="">
        {% csrf_token %}
        {{ form|materializecss }}
        <button class="btn waves-effect waves-light teal" type="submit" name="action">Add
            <i class="material-icons right">send</i>
        </button>
    </form>
</div>
<!-- end post form for modal -->

posts/templates/posts/_post_list.html
{% load humanize %}
{% load hitcount_tags %}

<div id="post-list">
    <div class="row">
        {% if post_list %}
        {% for post in post_list %}
        <!------------------- Post card -------------------->
        <div class="col s12 m6">
            <div class="card medium hoverable">
                <div class="card-image">
                    <img src="{{ post.image.url }}">
                    <span class="card-title"><b>{{ post.title|title }}</b></span>
                </div>
                <div class="card-content">
                    <p>{{ post.body|truncatewords:20 }}</p>
                </div>
                <div class="card-action">
                    <a href="{{ post.get_absolute_url }}" class="teal-text">Read
                    <span class="grey-text vertical-align right">
                        <i class="far fa-eye"></i>&nbsp;&nbsp;{% get_hit_count for post %} &nbsp;&#8226;
                        &nbsp;<i class="far fa-comment"></i>&nbsp;&nbsp;{{ post.comment_count }}
                  </span></a>
                </div>
            </div>
        </div>
        <!------------------- End Post card -------------------->
        {% endfor %}
    </div>
    {% else %}
    <div style="margin-bottom: 50px; margin-top: 50px; padding: 40px 0px; border: 4px #9e9e9e solid; border-style: dashed;"
         class="nopost-wrapper container center">
        <h5 style="padding: 10px; margin-top: 0px;" class="grey-text">No posts yet.</h5>
        <a href="{% url 'posts:create' %}" class="btn waves-effect grey">
            <i class="material-icons white-text left">add_circle</i>
            <span class="bold">Add a post</span>
        </a>
    </div>
    {% endif %}
</div>

posts/templates/posts/_posts_li.html
{% if post_list %}
<ul class="collection col s12 m6">
    {% for post in post_list %}
        <li>
            <a class="collection-item" href="{{ post.get_absolute_url }}"><b>{{post.title}}</b></a>
        </li>
        {% endfor %}
</ul>
{% else %}
<ul>
    <li><b>No results found</b></li>
</ul>
{% endif %}

posts/templates/posts/_recent_posts.html
{% load hitcount_tags %}
<h5 class="teal-text">Recent Posts</h5>
<div class="collection">
    {% for post in recent_posts %}
    <li class="collection-item avatar">
        <img src="{{ post.image_thumbnail.url }}" class="circle responsive-img">
        <a href="{{ post.get_absolute_url }}">
            <span class="title">{{ post.title|truncatechars:17 }}</span>
        </a>
        <p class="grey-text">{{ post.creator.userprofile.name }} <br>
            {{ post.added|timesince }} ago
        </p>
    </li>
    {% endfor %}
</div>

posts/templates/posts/base.html
{% load static %}
{% load materializecss %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">
    <head>
      <!-- HTMX CDN -->
        <script src="https://unpkg.com/htmx.org@1.8.0"></script>

        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Django</title>
    </head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

  <div class="navbar-fixed">
    <nav class="purple darken-3">
      <div class="container">
        <div class="nav-wrapper">
          <a href="/" class="brand-logo flow-text">Django</a>
          <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>

          <!-- <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a> -->
           <ul class="right hide-on-med-and-down">
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/">Posts</a>
            </li>
            {% if user.is_authenticated %}
            <li>
              <a href="{% url 'create' %}">Add+</a>
            </li>
            <li>
              <a href="{% url 'account_logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
              <a href="{% url 'account_login' %}">Login</a>
            </li>
            <li>
              <a href="{% url 'account_signup' %}">Signup</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </div>
  <!-- sidenav slideout -->
  <ul id="slide-out" class="sidenav">
    {% if user.is_authenticated %}
    <li><div class="user-view">
      <div class="background">
        <img src="{% static 'posts/images/office.jpg' %}">
      </div>
      <a href="#user"><img class="circle" src="{% static 'posts/images/user_avatar.jpg' %}"></a>
      <a href="#name"><span class="white-text name">{{ user.username }}</span></a>
      <a href="#email"><span class="white-text email">{{ user.email }}</span></a>
    </div></li>
    {% else %}
    <li><div class="user-view">
      <div class="background">
        <img src="{% static 'posts/images/office.jpg' %}">
      </div>
      <a href="#user"><img class="circle" src="{% static 'posts/images/user_avatar.jpg' %}"></a>
      <a href="#name"><span class="white-text name">User</span></a>
      <a href="#email"><span class="white-text email">example@gmail.com</span></a>
    </div></li>
    {% endif %}

    <li><a class="waves-effect" href="/"><i class="material-icons">home</i>Home</a></li>
    <li><a class="waves-effect" href="/"><i class="material-icons">list</i>Posts</a></li>
    <li><a class="waves-effect" href="{% url 'create' %}"><i class="material-icons">add</i>New Post</a></li>
    <li><div class="divider"></div></li>
    <li><a class="subheader">Account</a></li>
    {% if user.is_authenticated %}
      <li><a class="waves-effect" href="#!"><i class="material-icons">account_circle</i>Profile</a></li>
      <li><a class="waves-effect" href="{% url 'account_logout' %}"><i class="material-icons">highlight_off</i>Logout</a></li>
    {% else %}
      <li><a class="waves-effect" href="{% url 'account_login' %}"><i class="material-icons">exit_to_app</i>Login</a></li>
      <li><a class="waves-effect" href="{% url 'account_signup' %}"><i class="material-icons">launch</i>Signup</a></li>
    {% endif %}
  </ul>

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> -->
    
    <script>
        // insert csrf token when performing AJAX request 
        //document.body.addEventListener('htmx:configRequest', (event) => {
        //event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'; 
        //})
        // floatin action buttons init
          document.addEventListener('DOMContentLoaded', function() {
          var fab = document.querySelectorAll('.fixed-action-btn');
          var instances = M.FloatingActionButton.init(fab, {});
          });
        // end floating action buttons

        // dropdown
        document.addEventListener('DOMContentLoaded', function() {
        var drop = document.querySelectorAll('.dropdown-trigger');
        var instances = M.Dropdown.init(drop, {});
        });

        // Create Post Modal
        document.addEventListener('DOMContentLoaded', function() {
        var pmodal = document.querySelectorAll('.modal');
        var instances = M.Modal.init(pmodal, {});
        });

        // Materialize side nav init
        document.addEventListener('DOMContentLoaded', function() {
        var snav = document.querySelectorAll('.sidenav');
        var instances = M.Sidenav.init(snav, {});
        });

        /* date picker materialized css */
        document.addEventListener('DOMContentLoaded', function() {
        var dp = document.querySelectorAll('.datepicker');
        var instances = M.Datepicker.init(dp, {
          'isRTL': false
        });
        });

        // Materialized CSS Collapsible init
        document.addEventListener('DOMContentLoaded', function() {
        var collaps = document.querySelectorAll('.collapsible');
        var instances = M.Collapsible.init(collaps, {});
        });


        // Initialize collapsible (uncomment the lines below if you use the dropdown variation)
        // var collapsibleElem = document.querySelector('.collapsible');
        // var collapsibleInstance = M.Collapsible.init(collapsibleElem, {});

        // End of Materialize side nav

        
              // init materialized css auto complete with ajax
        // document.addEventListener('DOMContentLoaded', function() {
        //       $.get("/search/", function(data){
        //         console.log(data)
        //         // now init autocomplete
        //         let ac = document.querySelectorAll('.autocomplete');
        //         let instances = M.Autocomplete.init(ac, {
        //         data: JSON.parse(JSON.stringify(data))
        //         });
        //     });
        // });
        
        
    </script>
</body>
</html>

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Home{% endblock title %}

{% block content %}

<div class="row">
    {% comment %}
    <!-- Search autocomplete -->
    <div class="col s12">
        <div class="row">
            <form action="{% url 'posts:search' %}">
                <div class="input-field col s12">
                    <i class="material-icons teal-text prefix">search</i>
                    <input type="text" name="q" id="autocomplete-input" class="autocomplete">
                    <label for="autocomplete-input">Search</label>
                </div>
            </form>
        </div>
    </div>
    {% endcomment %}
    <div class="row">
        <div class="col s12">
            <h3 class="purple-text text-darken-3">Latest Posts
                <span><a href="{% url 'posts:create' %}" class="waves-effect waves-light btn-small teal">Add a post</a>
      </span></h3>
        </div>
    </div>

    <div id="post-add-form"></div>
    
    <div hx-get="/htmx_post_list"
        hx-trigger="load delay:0.3s"
        hx-swap="outerHTML"
        >
        <div class="htmx-indicator progress">
            <div class="indeterminate"></div>
        </div>
        </div>
    </div>

<!-- Pagination -->
{% if is_paginated %}
<div class="center">
  <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="waves-effect"><a href="?page=1"><i class="material-icons">first_page</i></a></li>
            <li class="waves-effect"><a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
            <li><a href="?page={{ page_obj.number|add:'-1' }}">{{ page_obj.number|add:'-1' }}</a></li>
        {% endif %}
            <li class="active"><a href="#">{{ page_obj.number }}</a></li>
        {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.number|add:'+1' }}">{{ page_obj.number|add:'+1' }}</a></li>
            <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
            <li class="waves-effect"><a href="?page={{ page_obj.paginator.num_pages }}"><i class="material-icons">last_page</i></a></li>
        {% endif %}
  </ul>
</div>
{% endif %}

    <div class="row">
        <div id="popular-posts" class="col s12 l6">
            {% include 'posts/_popular_posts.html' %}
        </div>
        <div id="recent-post" class="col s12 l6">
            {% include 'posts/_recent_posts.html' %}
        </div>
    </div>
    <!-- floating action buttons -->
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large purple darken-3">
            <i class="large material-icons">add</i>
        </a>
        <ul>
            <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
            <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
            <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
            <li><a href="{% url 'posts:create' %}" class="btn-floating modal-trigger red">
                <i class="material-icons">add</i></a>
            </li>
        </ul>
    </div>
    <!--  End floating action buttons -->

    {% endblock content %}